<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductImage;
use App\Models\ProductsAuthor;
use App\Models\ProductsCategory;
use App\Models\ProductStock;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    private const PLACEHOLDER_QUANTITY = 50;

    public function run(): void
    {
        $products = [
            [
                'title' => 'Astral Journey',
                'category' => 'Fantasy',
                'author' => 'Nathaniel Parker',
                'price' => 28.00,
                'rating' => 5,
                'bestseller' => true,
                'images' => ['book-image-24.webp'],
            ],
            [
                'title' => 'Best Italian Cuisines',
                'category' => 'Cooking',
                'author' => 'Nathaniel Parker',
                'price' => 25.00,
                'rating' => 4,
                'bestseller' => true,
                'images' => ['book-image-7.webp'],
            ],
            [
                'title' => 'Economic Opportunity',
                'category' => 'Business',
                'author' => 'Clara Whitfield',
                'price' => 22.00,
                'rating' => 5,
                'bestseller' => false,
                'images' => ['book-image-32.webp'],
            ],
            [
                'title' => 'Journey Through Time',
                'category' => 'History',
                'author' => 'Amelia Brooks',
                'price' => 19.00,
                'rating' => 4,
                'bestseller' => false,
                'images' => ['book-image-25.webp'],
            ],
            [
                'title' => 'Simple Aesthetics',
                'category' => 'Art & Design',
                'author' => 'Amelia Brooks',
                'price' => 32.00,
                'rating' => 5,
                'bestseller' => false,
                'images' => ['book-image-26.webp'],
            ],
            [
                'title' => 'The Silent Forest',
                'category' => 'Novels',
                'author' => 'Eleanor Finch',
                'price' => 21.00,
                'rating' => 3,
                'bestseller' => false,
                'images' => ['book-image-33.webp'],
            ],
            [
                'title' => 'Mind & Wellness',
                'category' => 'Self-help',
                'author' => 'Oliver Hartman',
                'price' => 15.00,
                'rating' => 4,
                'bestseller' => false,
                'images' => ['book-image-18.webp'],
            ],
            [
                'title' => 'The Language of Color',
                'category' => 'Art & Design',
                'author' => 'Oliver Hartman',
                'price' => 24.00,
                'rating' => 4,
                'bestseller' => false,
                'images' => ['cover-15.jpg'],
            ],
            [
                'title' => 'Modern Sculpture',
                'category' => 'Art & Design',
                'author' => 'Clara Whitfield',
                'price' => 29.50,
                'rating' => 5,
                'bestseller' => false,
                'images' => ['cover-30.jpg'],
            ],
            [
                'title' => 'Design Thinking',
                'category' => 'Art & Design',
                'author' => 'Henry Caldwell',
                'price' => 18.00,
                'rating' => 4,
                'bestseller' => false,
                'images' => ['cover-45.jpg'],
            ],
            [
                'title' => 'Visual Harmony',
                'category' => 'Art & Design',
                'author' => 'Amelia Brooks',
                'price' => 33.00,
                'rating' => 3,
                'bestseller' => false,
                'images' => ['cover-55.jpg'],
            ],
            [
                'title' => 'Empires of the Ancient World',
                'category' => 'History',
                'author' => 'Nathaniel Parker',
                'price' => 26.00,
                'rating' => 5,
                'bestseller' => true,
                'images' => ['cover-65.jpg'],
            ],
            [
                'title' => 'The Silk Road Chronicles',
                'category' => 'History',
                'author' => 'Eleanor Finch',
                'price' => 21.50,
                'rating' => 4,
                'bestseller' => false,
                'images' => ['cover-75.jpg'],
            ],
            [
                'title' => 'Revolutions That Shaped Us',
                'category' => 'History',
                'author' => 'Oliver Hartman',
                'price' => 17.00,
                'rating' => 4,
                'bestseller' => false,
                'images' => ['cover-85.jpg'],
            ],
            [
                'title' => 'Voices from the Past',
                'category' => 'History',
                'author' => 'Clara Whitfield',
                'price' => 20.00,
                'rating' => 3,
                'bestseller' => false,
                'images' => ['cover-100.jpg'],
            ],
            [
                'title' => 'The Quantum Frontier',
                'category' => 'Science',
                'author' => 'Henry Caldwell',
                'price' => 31.00,
                'rating' => 5,
                'bestseller' => true,
                'images' => ['cover-110.jpg'],
            ],
            [
                'title' => 'Life Under the Microscope',
                'category' => 'Science',
                'author' => 'Amelia Brooks',
                'price' => 23.00,
                'rating' => 4,
                'bestseller' => false,
                'images' => ['cover-130.jpg'],
            ],
            [
                'title' => 'Cosmic Origins',
                'category' => 'Science',
                'author' => 'Nathaniel Parker',
                'price' => 27.50,
                'rating' => 5,
                'bestseller' => false,
                'images' => ['cover-140.jpg'],
            ],
            [
                'title' => 'The Genetic Code',
                'category' => 'Science',
                'author' => 'Eleanor Finch',
                'price' => 19.50,
                'rating' => 3,
                'bestseller' => false,
                'images' => ['cover-165.jpg'],
            ],
            [
                'title' => 'Whispers in the Attic',
                'category' => 'Novels',
                'author' => 'Oliver Hartman',
                'price' => 14.00,
                'rating' => 4,
                'bestseller' => false,
                'images' => ['cover-175.jpg'],
            ],
            [
                'title' => 'The Last Letter',
                'category' => 'Novels',
                'author' => 'Clara Whitfield',
                'price' => 16.50,
                'rating' => 5,
                'bestseller' => true,
                'images' => ['cover-190.jpg'],
            ],
            [
                'title' => 'Shadows of Yesterday',
                'category' => 'Novels',
                'author' => 'Henry Caldwell',
                'price' => 18.50,
                'rating' => 4,
                'bestseller' => false,
                'images' => ['cover-210.jpg'],
            ],
            [
                'title' => 'A Quiet Reckoning',
                'category' => 'Novels',
                'author' => 'Amelia Brooks',
                'price' => 15.00,
                'rating' => 3,
                'bestseller' => false,
                'images' => ['cover-220.jpg'],
            ],
            [
                'title' => 'Rustic Italian Kitchen',
                'category' => 'Cooking',
                'author' => 'Nathaniel Parker',
                'price' => 22.00,
                'rating' => 5,
                'bestseller' => false,
                'images' => ['cover-235.jpg'],
            ],
            [
                'title' => 'The Art of Fermentation',
                'category' => 'Cooking',
                'author' => 'Eleanor Finch',
                'price' => 25.00,
                'rating' => 4,
                'bestseller' => false,
                'images' => ['cover-260.jpg'],
            ],
            [
                'title' => 'Spice Route Recipes',
                'category' => 'Cooking',
                'author' => 'Oliver Hartman',
                'price' => 20.50,
                'rating' => 4,
                'bestseller' => false,
                'images' => ['cover-275.jpg'],
            ],
            [
                'title' => 'Baking with Heart',
                'category' => 'Cooking',
                'author' => 'Clara Whitfield',
                'price' => 17.50,
                'rating' => 3,
                'bestseller' => false,
                'images' => ['cover-300.jpg'],
            ],
            [
                'title' => 'Rewire Your Mindset',
                'category' => 'Self-help',
                'author' => 'Henry Caldwell',
                'price' => 16.00,
                'rating' => 5,
                'bestseller' => true,
                'images' => ['cover-320.jpg'],
            ],
            [
                'title' => 'The Discipline of Focus',
                'category' => 'Self-help',
                'author' => 'Amelia Brooks',
                'price' => 14.50,
                'rating' => 4,
                'bestseller' => false,
                'images' => ['cover-330.jpg'],
            ],
            [
                'title' => 'Small Habits, Big Change',
                'category' => 'Self-help',
                'author' => 'Nathaniel Parker',
                'price' => 13.00,
                'rating' => 4,
                'bestseller' => false,
                'images' => ['cover-340.jpg'],
            ],
            [
                'title' => 'Finding Your Center',
                'category' => 'Self-help',
                'author' => 'Eleanor Finch',
                'price' => 18.00,
                'rating' => 3,
                'bestseller' => false,
                'images' => ['cover-350.jpg'],
            ],
            [
                'title' => 'Into the Wild Unknown',
                'category' => 'Adventure',
                'author' => 'Oliver Hartman',
                'price' => 21.00,
                'rating' => 5,
                'bestseller' => false,
                'images' => ['cover-360.jpg'],
            ],
            [
                'title' => "The Explorer's Notebook",
                'category' => 'Adventure',
                'author' => 'Clara Whitfield',
                'price' => 23.50,
                'rating' => 4,
                'bestseller' => false,
                'images' => ['cover-370.jpg'],
            ],
            [
                'title' => 'Beyond the Horizon',
                'category' => 'Adventure',
                'author' => 'Henry Caldwell',
                'price' => 19.00,
                'rating' => 4,
                'bestseller' => false,
                'images' => ['cover-380.jpg'],
            ],
            [
                'title' => 'Summit Fever',
                'category' => 'Adventure',
                'author' => 'Amelia Brooks',
                'price' => 25.50,
                'rating' => 3,
                'bestseller' => false,
                'images' => ['cover-390.jpg'],
            ],
            [
                'title' => "The Dragon's Oath",
                'category' => 'Fantasy',
                'author' => 'Nathaniel Parker',
                'price' => 27.00,
                'rating' => 5,
                'bestseller' => true,
                'images' => ['cover-400.jpg'],
            ],
            [
                'title' => 'Kingdom of Ash and Ember',
                'category' => 'Fantasy',
                'author' => 'Eleanor Finch',
                'price' => 29.00,
                'rating' => 5,
                'bestseller' => false,
                'images' => ['cover-410.jpg'],
            ],
            [
                'title' => 'The Last Sorcerer',
                'category' => 'Fantasy',
                'author' => 'Oliver Hartman',
                'price' => 22.50,
                'rating' => 4,
                'bestseller' => false,
                'images' => ['cover-420.jpg'],
            ],
            [
                'title' => 'Realm of Shattered Crowns',
                'category' => 'Fantasy',
                'author' => 'Clara Whitfield',
                'price' => 24.50,
                'rating' => 3,
                'bestseller' => false,
                'images' => ['cover-430.jpg'],
            ],
            [
                'title' => 'Meet Me at Midnight',
                'category' => 'Romance',
                'author' => 'Henry Caldwell',
                'price' => 15.50,
                'rating' => 4,
                'bestseller' => false,
                'images' => ['cover-440.jpg'],
            ],
            [
                'title' => 'The Paris Promise',
                'category' => 'Romance',
                'author' => 'Amelia Brooks',
                'price' => 17.00,
                'rating' => 5,
                'bestseller' => true,
                'images' => ['cover-450.jpg'],
            ],
            [
                'title' => 'Love in Every Season',
                'category' => 'Romance',
                'author' => 'Nathaniel Parker',
                'price' => 14.00,
                'rating' => 4,
                'bestseller' => false,
                'images' => ['cover-460.jpg'],
            ],
            [
                'title' => 'A Second Chance at Forever',
                'category' => 'Romance',
                'author' => 'Eleanor Finch',
                'price' => 16.00,
                'rating' => 3,
                'bestseller' => false,
                'images' => ['cover-480.jpg'],
            ],
            [
                'title' => 'The Startup Playbook',
                'category' => 'Business',
                'author' => 'Oliver Hartman',
                'price' => 28.00,
                'rating' => 5,
                'bestseller' => false,
                'images' => ['cover-490.jpg'],
            ],
            [
                'title' => 'Negotiate Like a Pro',
                'category' => 'Business',
                'author' => 'Clara Whitfield',
                'price' => 24.00,
                'rating' => 4,
                'bestseller' => false,
                'images' => ['cover-500.jpg'],
            ],
            [
                'title' => 'Scaling Smart',
                'category' => 'Business',
                'author' => 'Henry Caldwell',
                'price' => 30.00,
                'rating' => 4,
                'bestseller' => false,
                'images' => ['cover-510.jpg'],
            ],
            [
                'title' => 'The Leadership Edge',
                'category' => 'Business',
                'author' => 'Amelia Brooks',
                'price' => 26.50,
                'rating' => 5,
                'bestseller' => false,
                'images' => ['cover-520.jpg'],
            ],
        ];

        foreach ($products as $data) {
            $category = ProductsCategory::where('name', $data['category'])->firstOrFail();
            $author = ProductsAuthor::where('name', $data['author'])->firstOrFail();

            $product = Product::firstOrCreate(
                ['slug' => Str::slug($data['title'])],
                [
                    'category_id' => $category->id,
                    'author_id' => $author->id,
                    'title' => $data['title'],
                    'short_description' => $data['short_description'] ?? null,
                    'description' => $data['description'] ?? null,
                    'rating_avg' => $data['rating'],
                    'bestseller' => $data['bestseller'] ? 1 : 0,
                    'status' => 1,
                    'published_at' => now(),
                ],
            );

            foreach ($data['images'] as $sort => $image) {
                ProductImage::firstOrCreate(
                    [
                        'product_id' => $product->id,
                        'sort_order' => $sort + 1,
                    ],
                    ['image' => ['original' => "products/{$image}"]],
                );
            }

            ProductStock::firstOrCreate(
                [
                    'product_id' => $product->id,
                    'status' => 1,
                ],
                [
                    'quantity' => self::PLACEHOLDER_QUANTITY,
                    'price' => $data['price'],
                    'sort_order' => 1,
                ],
            );
        }
    }
}
